jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secrets
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          example-command "$super_secret"
