on: 
  push:
    branches:
    - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          example-command "$SUPER_SECRET"
